<?php


namespace App\Http\Requests\General\Auth\Roles;


use Illuminate\Foundation\Http\FormRequest;

class UpdateRoleRequest extends FormRequest
{
    public function authorize()
    {
//        return Gate::allows('admin.');
        return true;
    }

    public function rules()
    {
        return [
            'name' => 'string | required ',
            'description' => 'string | required ',
        ];

    }

    public function validationData()
    {
        return $this->json()->all(); // TODO: Change the autogenerated stub
    }

}
