<?php


namespace App\Http\Requests\General\Auth\General;


class LoginUsingPhoneNumberRequest
{

    public function rules()
    {
        return [
            'mobile_phone' => 'required|string|exists:users,mobile_phone,deleted_at,NULL',
            'password' => 'required',
        ];
    }
    public function validationData():array
    {
        return $this->json()->all(); // TODO: Change the autogenerated stub
    }

}
