<?php


namespace App\Http\Requests\General\Auth\General;


use Illuminate\Foundation\Http\FormRequest;

class LoginUsingEmailRequest extends FormRequest
{

    public function rules()
    {
        return [
            'email' => 'required|email|exists:users,email',
            'password' => 'required',
        ];
    }
    public function validationData():array
    {
        return $this->json()->all(); // TODO: Change the autogenerated stub
    }

}
