<?php


namespace App\Http\Requests\General\Auth\General;


use Illuminate\Foundation\Http\FormRequest;

class LoginUsingUsernameRequest extends FormRequest
{

    public function rules()
    {
        return [
            'username' => 'required|string|exists:users,username',
            'password' => 'required',
        ];
    }
    public function validationData():array
    {
        return $this->json()->all(); // TODO: Change the autogenerated stub
    }

}
